### ISSUE TITLE
MQTT Server with user + password

### ISSUE THREAD

**Issue by svenerbe** [peuter/ecoflow#6]
Hi, is there as well a option to specify a mqtt server user + password? for the homie.mqtt.paho_mqtt_client. i get for my mqtt server a None Connection refused - not authorised.

**Comment by peuter** [comment]
Haven't added that initially, because my local broker does not required credentials. I added that without being able to test it. Please check if it works and close the issue again if it does

**Comment by svenerbe** [comment]
Hi, its working - many thanks for the fast update. i see now the messages in mqtt. question is now how can i get this data into homeassitant. but this is another topic.

**Comment by peuter** [comment]
I never used homeassistant, but if it supports the homie standard somehow, that should be easy.
